# Generated by Django 2.1.3 on 2018-11-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mobile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_phone',
        ),
    ]
