# Generated by Django 2.1.3 on 2018-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='comulative_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
