# Generated by Django 2.1.3 on 2018-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_player_comulative_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_games',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_loose',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
