# Generated by Django 2.1.3 on 2018-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0002_auto_20181119_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfPlayers', models.IntegerField(default=0)),
                ('catagory_id', models.IntegerField(default=0)),
                ('questions', models.TextField()),
            ],
        ),
    ]
