# Generated by Django 2.1.3 on 2018-11-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20181127_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(max_length=255)),
                ('question_id', models.TextField(max_length=255)),
                ('Answer', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(max_length=255)),
                ('question_id', models.TextField(max_length=255)),
                ('Answer_id', models.TextField(max_length=255)),
            ],
        ),
    ]
