# Generated by Django 2.1.3 on 2018-11-25 16:02

import content.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('name_ar', models.CharField(max_length=35)),
                ('age_rating', models.CharField(max_length=3)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Maximum Limit is 5')])),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=35, null=True)),
                ('age_rating', models.CharField(max_length=3)),
                ('Correct_answer', models.CharField(max_length=150)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Maximum Limit is 5')])),
                ('Category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Category')),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=content.models.get_image_path)),
                ('Question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Image', to='content.QuestionImage'),
        ),
    ]
