# Generated by Django 2.1.3 on 2018-11-19 20:37

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=content.models.get_image_path)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='parent',
            new_name='Category_parent',
        ),
        migrations.AddField(
            model_name='questionimage',
            name='Question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Image', to='content.QuestionImage'),
        ),
    ]
