# Generated by Django 2.1.3 on 2018-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='representation',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=35),
        ),
    ]
