# Generated by Django 2.1.3 on 2019-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20190416_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTmpTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
