# Generated by Django 2.1.3 on 2019-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontmp',
            name='Approved',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='questiontmp',
            name='Disapproved',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
