# Generated by Django 2.1.3 on 2019-04-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20190416_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontmp',
            old_name='Disapproved',
            new_name='Disapprovedd',
        ),
    ]
