# Generated by Django 2.1.3 on 2019-04-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20190416_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontmp',
            old_name='Disapprovedd',
            new_name='Disapproveddddddd',
        ),
    ]
