# Generated by Django 2.1.3 on 2019-04-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20190416_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontmp',
            old_name='Disapproveddddddd',
            new_name='Disapprovedd',
        ),
    ]
