# Generated by Django 2.1.3 on 2019-04-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20190416_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontmp',
            name='Approved',
        ),
    ]
