# Generated by Django 2.1.3 on 2019-04-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_questiontmp_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontmp',
            name='Disapprovedd',
        ),
        migrations.AddField(
            model_name='questiontmp',
            name='year_in_school',
            field=models.CharField(choices=[('-', '-'), ('AP', 'AP'), ('DP', 'DP')], default='-', max_length=2),
        ),
    ]
