# Generated by Django 2.1.3 on 2019-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20190416_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionTmpTmp',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='questiontmp',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='questiontmp',
            name='Approval',
            field=models.CharField(choices=[('-', '-'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='-', max_length=15),
        ),
    ]
