# Generated by Django 2.1.3 on 2019-04-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20190416_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontmp',
            name='disapproved',
        ),
        migrations.RemoveField(
            model_name='questiontmp',
            name='is_approved',
        ),
    ]
